plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\mrozo\\OneDrive - Sistemas de Información geográfica (SIg)\\Mapas y Estadisticas\\DATAPAC\\apps\\reporte"
publishOrigin = "default"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]